# -*- coding: utf-8 -*-
"""HIST-Thresh_DIP_HarshithaGovindaraju.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-AnNVCc-vH2mIJ9WL6x5_Klg1EJwkSYG
"""

# Commented out IPython magic to ensure Python compatibility.
from __future__ import print_function
import matplotlib.pyplot as plt
# %matplotlib inline

import argparse
import os
# os.environ['CUDA_VISIBLE_DEVICES'] = '1'

import numpy as np


import torch
import torch.optim

from skimage.metrics import peak_signal_noise_ratio as compare_psnr

torch.backends.cudnn.enabled = True
torch.backends.cudnn.benchmark =True
dtype = torch.cuda.FloatTensor

imsize = -1
factor = 4 # 8
enforse_div32 = 'CROP'
PLOT = True

import torch.nn as nn
import torchvision
import sys

import numpy as np
from PIL import Image
import PIL
import numpy as np


def crop_image(img, d=32):
    '''Make dimensions divisible by `d`'''

    new_size = (img.size[0] - img.size[0] % d,
                img.size[1] - img.size[1] % d)

    bbox = [
            int((img.size[0] - new_size[0])/2),
            int((img.size[1] - new_size[1])/2),
            int((img.size[0] + new_size[0])/2),
            int((img.size[1] + new_size[1])/2),
    ]

    img_cropped = img.crop(bbox)
    return img_cropped

def get_params(opt_over, net, net_input, downsampler=None):
    '''Returns parameters that we want to optimize over.

    Args:
        opt_over: comma separated list, e.g. "net,input" or "net"
        net: network
        net_input: torch.Tensor that stores input `z`
    '''
    opt_over_list = opt_over.split(',')
    params = []

    for opt in opt_over_list:

        if opt == 'net':
            params += [x for x in net.parameters() ]
        elif  opt=='down':
            assert downsampler is not None
            params = [x for x in downsampler.parameters()]
        elif opt == 'input':
            net_input.requires_grad = True
            params += [net_input]
        else:
            assert False, 'what is it?'

    return params

def get_image_grid(images_np, nrow=8):
    '''Creates a grid from a list of images by concatenating them.'''
    images_torch = [torch.from_numpy(x) for x in images_np]
    torch_grid = torchvision.utils.make_grid(images_torch, nrow)

    return torch_grid.numpy()

def plot_image_grid(images_np, nrow =8, factor=1, interpolation='lanczos'):
    """Draws images in a grid

    Args:
        images_np: list of images, each image is np.array of size 3xHxW of 1xHxW
        nrow: how many images will be in one row
        factor: size if the plt.figure
        interpolation: interpolation used in plt.imshow
    """
    n_channels = max(x.shape[0] for x in images_np)
    assert (n_channels == 3) or (n_channels == 1), "images should have 1 or 3 channels"

    images_np = [x if (x.shape[0] == n_channels) else np.concatenate([x, x, x], axis=0) for x in images_np]

    grid = get_image_grid(images_np, nrow)

    plt.figure(figsize=(len(images_np) + factor, 12 + factor))

    if images_np[0].shape[0] == 1:
        plt.imshow(grid[0], cmap='gray', interpolation=interpolation)
    else:
        plt.imshow(grid.transpose(1, 2, 0), interpolation=interpolation)

    plt.show()

    return grid

def load(path):
    """Load PIL image."""
    img = Image.open(path)
    return img

def get_image(path, imsize=-1):
    """Load an image and resize to a cpecific size.

    Args:
        path: path to image
        imsize: tuple or scalar with dimensions; -1 for `no resize`
    """
    img = load(path)

    if isinstance(imsize, int):
        imsize = (imsize, imsize)

    if imsize[0]!= -1 and img.size != imsize:
        if imsize[0] > img.size[0]:
            img = img.resize(imsize, Image.BICUBIC)
        else:
            img = img.resize(imsize, Image.ANTIALIAS)

    img_np = pil_to_np(img)

    return img, img_np



def fill_noise(x, noise_type):
    """Fills tensor `x` with noise of type `noise_type`."""
    if noise_type == 'u':
        x.uniform_()
    elif noise_type == 'n':
        x.normal_()
    else:
        assert False

def get_noise(input_depth, method, spatial_size, noise_type='u', var=1./10):
    """Returns a pytorch.Tensor of size (1 x `input_depth` x `spatial_size[0]` x `spatial_size[1]`)
    initialized in a specific way.
    Args:
        input_depth: number of channels in the tensor
        method: `noise` for fillting tensor with noise; `meshgrid` for np.meshgrid
        spatial_size: spatial size of the tensor to initialize
        noise_type: 'u' for uniform; 'n' for normal
        var: a factor, a noise will be multiplicated by. Basically it is standard deviation scaler.
    """
    if isinstance(spatial_size, int):
        spatial_size = (spatial_size, spatial_size)
    if method == 'noise':
        shape = [1, input_depth, spatial_size[0], spatial_size[1]]
        net_input = torch.zeros(shape)

        fill_noise(net_input, noise_type)
        net_input *= var
    else:
        assert False

    return net_input

def pil_to_np(img_PIL):
    '''Converts image in PIL format to np.array.

    From W x H x C [0...255] to C x W x H [0..1]
    '''
    ar = np.array(img_PIL)

    if len(ar.shape) == 3:
        ar = ar.transpose(2,0,1)
    else:
        ar = ar[None, ...]

    return ar.astype(np.float32) / 255.

def np_to_pil(img_np):
    '''Converts image in np.array format to PIL image.

    From C x W x H [0..1] to  W x H x C [0...255]
    '''
    ar = np.clip(img_np*255,0,255).astype(np.uint8)

    if img_np.shape[0] == 1:
        ar = ar[0]
    else:
        ar = ar.transpose(1, 2, 0)

    return Image.fromarray(ar)

def np_to_torch(img_np):
    '''Converts image in numpy.array to torch.Tensor.

    From C x W x H [0..1] to  C x W x H [0..1]
    '''
    return torch.from_numpy(img_np)[None, :]

def torch_to_np(img_var):
    '''Converts an image in torch.Tensor format to np.array.

    From 1 x C x W x H [0..1] to  C x W x H [0..1]
    '''
    return img_var.detach().cpu().numpy()[0]

# For known iteration
def optimize(optimizer_type, parameters, closure, LR, num_iter):
    if optimizer_type == 'adam':
        print('Starting optimization with ADAM')
        optimizer = torch.optim.Adam(parameters, lr=LR)

        for j in range(num_iter):
            optimizer.zero_grad()
            closure()
            optimizer.step()
    else:
        assert False

# For early stopping
# def optimize(optimizer_type, parameters, closure, LR, num_iter):
#     if optimizer_type == 'adam':
#         print('Starting optimization with ADAM')
#         optimizer = torch.optim.Adam(parameters, lr=LR)

#         for j in range(num_iter):
#             optimizer.zero_grad()
#             current_psnr = closure()  # capture PSNR from closure()
#             optimizer.step()

#             # Early stopping if PSNR >= 45 dB
#             if current_psnr >= 45:
#                 print(f"Stopping early at iteration {j} because PSNR reached {current_psnr:.2f} dB")
#                 break
#     else:
#         assert False, "Unsupported optimizer type!"

def put_in_center(img_np, target_size):
    img_out = np.zeros([3, target_size[0], target_size[1]])

    bbox = [
            int((target_size[0] - img_np.shape[1]) / 2),
            int((target_size[1] - img_np.shape[2]) / 2),
            int((target_size[0] + img_np.shape[1]) / 2),
            int((target_size[1] + img_np.shape[2]) / 2),
    ]

    img_out[:, bbox[0]:bbox[2], bbox[1]:bbox[3]] = img_np

    return img_out


def load_LR_HR_imgs_sr(fname, imsize, factor, enforse_div32=None):
    '''Loads an image, resizes it, center crops and downscales.

    Args:
        fname: path to the image
        imsize: new size for the image, -1 for no resizing
        factor: downscaling factor
        enforse_div32: if 'CROP' center crops an image, so that its dimensions are divisible by 32.
    '''
    img_orig_pil, img_orig_np = get_image(fname, -1)

    if imsize != -1:
        img_orig_pil, img_orig_np = get_image(fname, imsize)

    # For comparison with GT
    if enforse_div32 == 'CROP':
        new_size = (img_orig_pil.size[0] - img_orig_pil.size[0] % 32,
                    img_orig_pil.size[1] - img_orig_pil.size[1] % 32)

        bbox = [
                (img_orig_pil.size[0] - new_size[0])/2,
                (img_orig_pil.size[1] - new_size[1])/2,
                (img_orig_pil.size[0] + new_size[0])/2,
                (img_orig_pil.size[1] + new_size[1])/2,
        ]

        img_HR_pil = img_orig_pil.crop(bbox)
        img_HR_np = pil_to_np(img_HR_pil)
    else:
        img_HR_pil, img_HR_np = img_orig_pil, img_orig_np

    LR_size = [
               img_HR_pil.size[0] // factor,
               img_HR_pil.size[1] // factor
    ]

    img_LR_pil = img_HR_pil.resize(LR_size, Image.Resampling.LANCZOS)
    img_LR_np = pil_to_np(img_LR_pil)

    print('HR and LR resolutions: %s, %s' % (str(img_HR_pil.size), str (img_LR_pil.size)))

    return {
                'orig_pil': img_orig_pil,
                'orig_np':  img_orig_np,
                'LR_pil':  img_LR_pil,
                'LR_np': img_LR_np,
                'HR_pil':  img_HR_pil,
                'HR_np': img_HR_np
           }


def get_baselines(img_LR_pil, img_HR_pil):
    '''Gets `bicubic`, sharpened bicubic and `nearest` baselines.'''
    img_bicubic_pil = img_LR_pil.resize(img_HR_pil.size, Image.BICUBIC)
    img_bicubic_np = pil_to_np(img_bicubic_pil)

    img_nearest_pil = img_LR_pil.resize(img_HR_pil.size, Image.NEAREST)
    img_nearest_np = pil_to_np(img_nearest_pil)

    img_bic_sharp_pil = img_bicubic_pil.filter(PIL.ImageFilter.UnsharpMask())
    img_bic_sharp_np = pil_to_np(img_bic_sharp_pil)

    return img_bicubic_np, img_bic_sharp_np, img_nearest_np



def tv_loss(x, beta = 0.5):
    '''Calculates TV loss for an image `x`.

    Args:
        x: image, torch.Variable of torch.Tensor
        beta: See https://arxiv.org/abs/1412.0035 (fig. 2) to see effect of `beta`
    '''
    dh = torch.pow(x[:,:,:,1:] - x[:,:,:,:-1], 2)
    dw = torch.pow(x[:,:,1:,:] - x[:,:,:-1,:], 2)

    return torch.sum(torch.pow(dh[:, :, :-1] + dw[:, :, :, :-1], beta))

def skip(
        num_input_channels=2, num_output_channels=3,
        num_channels_down=[16, 32, 64, 128, 128], num_channels_up=[16, 32, 64, 128, 128], num_channels_skip=[4, 4, 4, 4, 4],
        filter_size_down=3, filter_size_up=3, filter_skip_size=1,
        need_sigmoid=True, need_bias=True,
        pad='zero', upsample_mode='nearest', downsample_mode='stride', act_fun='LeakyReLU',
        need1x1_up=True):
    """Assembles encoder-decoder with skip connections.

    Arguments:
        act_fun: Either string 'LeakyReLU|Swish|ELU|none' or module (e.g. nn.ReLU)
        pad (string): zero|reflection (default: 'zero')
        upsample_mode (string): 'nearest|bilinear' (default: 'nearest')
        downsample_mode (string): 'stride|avg|max|lanczos2' (default: 'stride')

    """
    assert len(num_channels_down) == len(num_channels_up) == len(num_channels_skip)

    n_scales = len(num_channels_down)

    if not (isinstance(upsample_mode, list) or isinstance(upsample_mode, tuple)) :
        upsample_mode   = [upsample_mode]*n_scales

    if not (isinstance(downsample_mode, list)or isinstance(downsample_mode, tuple)):
        downsample_mode   = [downsample_mode]*n_scales

    if not (isinstance(filter_size_down, list) or isinstance(filter_size_down, tuple)) :
        filter_size_down   = [filter_size_down]*n_scales

    if not (isinstance(filter_size_up, list) or isinstance(filter_size_up, tuple)) :
        filter_size_up   = [filter_size_up]*n_scales

    last_scale = n_scales - 1

    cur_depth = None

    model = nn.Sequential()
    model_tmp = model

    input_depth = num_input_channels
    for i in range(len(num_channels_down)):

        deeper = nn.Sequential()
        skip = nn.Sequential()

        if num_channels_skip[i] != 0:
            model_tmp.add(Concat(1, skip, deeper))
        else:
            model_tmp.add(deeper)

        model_tmp.add(bn(num_channels_skip[i] + (num_channels_up[i + 1] if i < last_scale else num_channels_down[i])))

        if num_channels_skip[i] != 0:
            skip.add(conv(input_depth, num_channels_skip[i], filter_skip_size, bias=need_bias, pad=pad))
            skip.add(bn(num_channels_skip[i]))
            skip.add(act(act_fun))

        # skip.add(Concat(2, GenNoise(nums_noise[i]), skip_part))

        deeper.add(conv(input_depth, num_channels_down[i], filter_size_down[i], 2, bias=need_bias, pad=pad, downsample_mode=downsample_mode[i]))
        deeper.add(bn(num_channels_down[i]))
        deeper.add(act(act_fun))

        deeper.add(conv(num_channels_down[i], num_channels_down[i], filter_size_down[i], bias=need_bias, pad=pad))
        deeper.add(bn(num_channels_down[i]))
        deeper.add(act(act_fun))

        deeper_main = nn.Sequential()

        if i == len(num_channels_down) - 1:
            # The deepest
            k = num_channels_down[i]
        else:
            deeper.add(deeper_main)
            k = num_channels_up[i + 1]

        deeper.add(nn.Upsample(scale_factor=2, mode=upsample_mode[i]))

        model_tmp.add(conv(num_channels_skip[i] + k, num_channels_up[i], filter_size_up[i], 1, bias=need_bias, pad=pad))
        model_tmp.add(bn(num_channels_up[i]))
        model_tmp.add(act(act_fun))


        if need1x1_up:
            model_tmp.add(conv(num_channels_up[i], num_channels_up[i], 1, bias=need_bias, pad=pad))
            model_tmp.add(bn(num_channels_up[i]))
            model_tmp.add(act(act_fun))

        input_depth = num_channels_down[i]
        model_tmp = deeper_main

    model.add(conv(num_channels_up[0], num_output_channels, 1, bias=need_bias, pad=pad))
    if need_sigmoid:
        model.add(nn.Sigmoid())

    return model

def get_net(input_depth, NET_TYPE, pad, upsample_mode, n_channels=3, act_fun='LeakyReLU', skip_n33d=128, skip_n33u=128, skip_n11=4, num_scales=5, downsample_mode='stride'):

    if NET_TYPE == 'skip':
        net = skip(input_depth, n_channels, num_channels_down = [skip_n33d]*num_scales if isinstance(skip_n33d, int) else skip_n33d,
                                            num_channels_up =   [skip_n33u]*num_scales if isinstance(skip_n33u, int) else skip_n33u,
                                            num_channels_skip = [skip_n11]*num_scales if isinstance(skip_n11, int) else skip_n11,
                                            upsample_mode=upsample_mode, downsample_mode=downsample_mode,
                                            need_sigmoid=True, need_bias=True, pad=pad, act_fun=act_fun)
    else:
        assert False

    return net

class Downsampler(nn.Module):
    '''
        http://www.realitypixels.com/turk/computergraphics/ResamplingFilters.pdf
    '''
    def __init__(self, n_planes, factor, kernel_type, phase=0, kernel_width=None, support=None, sigma=None, preserve_size=False):
        super(Downsampler, self).__init__()

        assert phase in [0, 0.5], 'phase should be 0 or 0.5'

        if kernel_type == 'lanczos2':
            support = 2
            kernel_width = 4 * factor + 1
            kernel_type_ = 'lanczos'

        elif kernel_type == 'lanczos3':
            support = 3
            kernel_width = 6 * factor + 1
            kernel_type_ = 'lanczos'

        elif kernel_type == 'gauss12':
            kernel_width = 7
            sigma = 1/2
            kernel_type_ = 'gauss'

        elif kernel_type == 'gauss1sq2':
            kernel_width = 9
            sigma = 1./np.sqrt(2)
            kernel_type_ = 'gauss'

        elif kernel_type in ['lanczos', 'gauss', 'box']:
            kernel_type_ = kernel_type

        else:
            assert False, 'wrong name kernel'


        # note that `kernel width` will be different to actual size for phase = 1/2
        self.kernel = get_kernel(factor, kernel_type_, phase, kernel_width, support=support, sigma=sigma)

        downsampler = nn.Conv2d(n_planes, n_planes, kernel_size=self.kernel.shape, stride=factor, padding=0)
        downsampler.weight.data[:] = 0
        downsampler.bias.data[:] = 0

        kernel_torch = torch.from_numpy(self.kernel)
        for i in range(n_planes):
            downsampler.weight.data[i, i] = kernel_torch

        self.downsampler_ = downsampler

        if preserve_size:

            if  self.kernel.shape[0] % 2 == 1:
                pad = int((self.kernel.shape[0] - 1) / 2.)
            else:
                pad = int((self.kernel.shape[0] - factor) / 2.)

            self.padding = nn.ReplicationPad2d(pad)

        self.preserve_size = preserve_size

    def forward(self, input):
        if self.preserve_size:
            x = self.padding(input)
        else:
            x= input
        self.x = x
        return self.downsampler_(x)

def get_kernel(factor, kernel_type, phase, kernel_width, support=None, sigma=None):
    assert kernel_type in ['lanczos', 'gauss', 'box']

    # factor  = float(factor)
    if phase == 0.5 and kernel_type != 'box':
        kernel = np.zeros([kernel_width - 1, kernel_width - 1])
    else:
        kernel = np.zeros([kernel_width, kernel_width])


    if kernel_type == 'box':
        assert phase == 0.5, 'Box filter is always half-phased'
        kernel[:] = 1./(kernel_width * kernel_width)

    elif kernel_type == 'gauss':
        assert sigma, 'sigma is not specified'
        assert phase != 0.5, 'phase 1/2 for gauss not implemented'

        center = (kernel_width + 1.)/2.
        print(center, kernel_width)
        sigma_sq =  sigma * sigma

        for i in range(1, kernel.shape[0] + 1):
            for j in range(1, kernel.shape[1] + 1):
                di = (i - center)/2.
                dj = (j - center)/2.
                kernel[i - 1][j - 1] = np.exp(-(di * di + dj * dj)/(2 * sigma_sq))
                kernel[i - 1][j - 1] = kernel[i - 1][j - 1]/(2. * np.pi * sigma_sq)
    elif kernel_type == 'lanczos':
        assert support, 'support is not specified'
        center = (kernel_width + 1) / 2.

        for i in range(1, kernel.shape[0] + 1):
            for j in range(1, kernel.shape[1] + 1):

                if phase == 0.5:
                    di = abs(i + 0.5 - center) / factor
                    dj = abs(j + 0.5 - center) / factor
                else:
                    di = abs(i - center) / factor
                    dj = abs(j - center) / factor


                pi_sq = np.pi * np.pi

                val = 1
                if di != 0:
                    val = val * support * np.sin(np.pi * di) * np.sin(np.pi * di / support)
                    val = val / (np.pi * np.pi * di * di)

                if dj != 0:
                    val = val * support * np.sin(np.pi * dj) * np.sin(np.pi * dj / support)
                    val = val / (np.pi * np.pi * dj * dj)

                kernel[i - 1][j - 1] = val


    else:
        assert False, 'wrong method name'

    kernel /= kernel.sum()

    return kernel

def add_module(self, module):
    self.add_module(str(len(self) + 1), module)

torch.nn.Module.add = add_module

class Concat(nn.Module):
    def __init__(self, dim, *args):
        super(Concat, self).__init__()
        self.dim = dim

        for idx, module in enumerate(args):
            self.add_module(str(idx), module)

    def forward(self, input):
        inputs = []
        for module in self._modules.values():
            inputs.append(module(input))

        inputs_shapes2 = [x.shape[2] for x in inputs]
        inputs_shapes3 = [x.shape[3] for x in inputs]

        if np.all(np.array(inputs_shapes2) == min(inputs_shapes2)) and np.all(np.array(inputs_shapes3) == min(inputs_shapes3)):
            inputs_ = inputs
        else:
            target_shape2 = min(inputs_shapes2)
            target_shape3 = min(inputs_shapes3)

            inputs_ = []
            for inp in inputs:
                diff2 = (inp.size(2) - target_shape2) // 2
                diff3 = (inp.size(3) - target_shape3) // 2
                inputs_.append(inp[:, :, diff2: diff2 + target_shape2, diff3:diff3 + target_shape3])

        return torch.cat(inputs_, dim=self.dim)

    def __len__(self):
        return len(self._modules)


class GenNoise(nn.Module):
    def __init__(self, dim2):
        super(GenNoise, self).__init__()
        self.dim2 = dim2

    def forward(self, input):
        a = list(input.size())
        a[1] = self.dim2
        # print (input.data.type())

        b = torch.zeros(a).type_as(input.data)
        b.normal_()

        x = torch.autograd.Variable(b)

        return x


class Swish(nn.Module):

    def __init__(self):
        super(Swish, self).__init__()
        self.s = nn.Sigmoid()

    def forward(self, x):
        return x * self.s(x)


def act(act_fun = 'LeakyReLU'):
    if isinstance(act_fun, str):
        if act_fun == 'LeakyReLU':
            return nn.LeakyReLU(0.2, inplace=True)
        elif act_fun == 'Swish':
            return Swish()
        elif act_fun == 'ELU':
            return nn.ELU()
        elif act_fun == 'none':
            return nn.Sequential()
        else:
            assert False
    else:
        return act_fun()


def bn(num_features):
    return nn.BatchNorm2d(num_features)


def conv(in_f, out_f, kernel_size, stride=1, bias=True, pad='zero', downsample_mode='stride'):
    downsampler = None
    if stride != 1 and downsample_mode != 'stride':

        if downsample_mode == 'avg':
            downsampler = nn.AvgPool2d(stride, stride)
        elif downsample_mode == 'max':
            downsampler = nn.MaxPool2d(stride, stride)
        elif downsample_mode  in ['lanczos2', 'lanczos3']:
            downsampler = Downsampler(n_planes=out_f, factor=stride, kernel_type=downsample_mode, phase=0.5, preserve_size=True)
        else:
            assert False

        stride = 1

    padder = None
    to_pad = int((kernel_size - 1) / 2)
    if pad == 'reflection':
        padder = nn.ReflectionPad2d(to_pad)
        to_pad = 0

    convolver = nn.Conv2d(in_f, out_f, kernel_size, stride, padding=to_pad, bias=bias)


    layers = filter(lambda x: x is not None, [padder, convolver, downsampler])
    return nn.Sequential(*layers)

"""# Load image and baselines"""

imgs = load_LR_HR_imgs_sr('/content/shaky.tif', imsize, factor, enforse_div32)

input_depth = 32

INPUT =     'noise'
pad   =     'reflection'
OPT_OVER =  'net'
KERNEL_TYPE='lanczos2'

LR = 0.001
tv_weight = 0.0

OPTIMIZER = 'adam'

num_iter = 2000

# net_input = get_noise(input_depth, INPUT, (imgs['HR_pil'].size[1], imgs['HR_pil'].size[0])).type(dtype).detach()

net = get_net(input_depth, 'skip' , pad,
              skip_n33d=128,
              skip_n33u=128,
              skip_n11=4,
              num_scales=5,
              upsample_mode='bilinear').type(dtype)

# Losses
mse = torch.nn.MSELoss().type(dtype)

downsampler = Downsampler(n_planes=3, factor=factor, kernel_type=KERNEL_TYPE, phase=0.5, preserve_size=True).type(dtype)

print(torch.__version__)
print(torch.cuda.is_available())

"""### Histogram Based **Thresholding**

#Manual Entry
"""

import cv2

def compute_histogram(image_path):
    # Load image in grayscale mode
    image = cv2.imread(image_path, 0)

    # Compute histogram
    hist = cv2.calcHist([image], [0], None, [256], [0, 256])

    # Display histogram
    plt.figure()
    plt.title("Grayscale Histogram")
    plt.xlabel("Bins")
    plt.ylabel("# of Pixels")
    plt.plot(hist)
    plt.xlim([0, 256])
    plt.show()

    return image, hist

def apply_threshold(image, threshold):
    # Apply a threshold
    _, mask = cv2.threshold(image, threshold, 255, cv2.THRESH_BINARY)

    # Display images
    plt.figure()
    plt.subplot(1, 2, 1)
    plt.title("Original Image")
    plt.imshow(image, cmap='gray')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.title("Mask Image")
    plt.imshow(mask, cmap='gray')
    plt.axis('off')

    plt.show()

    return mask

# Path to your image
image_path = '/content/shaky.tif'

# Compute histogram and load image
image, hist = compute_histogram(image_path)

# Choose a threshold value based on histogram analysis
threshold_value = 143  # Manual entry

# Apply threshold to create mask
mask = apply_threshold(image, threshold_value)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

import torch
from torchvision.transforms import ToTensor, ToPILImage
from PIL import Image
from IPython.display import display

def multiply_images_torch(image_path1, image_path2):
    # Load images
    img1 = imgs['LR_pil']
    img2 = Image.fromarray(image_path2).convert('RGB')
    img3 = imgs['HR_pil']

    # Resize image2 to image1's size if they differ
    if img1.size != img2.size:
        img2 = img2.resize(img1.size, Image.BICUBIC)

    # Convert images to tensors
    tensor1 = ToTensor()(img1)
    tensor2 = ToTensor()(img2)

    # Weight the images
    tensor1 *= 1
    tensor2 *= 1

    # Add weighted images, ensuring the result is clamped between 0 and 1 to remain a valid image
    result_tensor = torch.clamp(tensor1 + tensor2, min=0, max=1)

    # Multiply images
    result_tensor = tensor1 * tensor2

    # Convert tensor to PIL Image
    result_image = ToPILImage()(result_tensor)
    result_image.show()
    return result_image, result_tensor

result_image,result_tensor = multiply_images_torch(imgs['LR_pil'], (mask))
display(result_image)
# result_image.save('/path/to/output.jpg')
result_tensor = result_tensor.unsqueeze(0).to(device)

import torch
from PIL import Image
import torchvision.transforms as transforms
from PIL import Image

# Increase the maximum number of pixels
Image.MAX_IMAGE_PIXELS = None  # This removes the limit entirely, use with caution

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
net = net.to(device)


# Load the image
image = Image.open('/content/shaky.tif').convert("L")  # Convert to grayscale if necessary
print(f"Original image size: {image.size}")

# Define the transformation
transform = transforms.Compose([
    transforms.Resize((1184, 896)),  # Resize the image
    transforms.ToTensor()            # Convert the image to a tensor for the given model
])

# Apply the transformation
image_tensor = transform(image)
image_tensor = image_tensor.to(device)
# Since the required shape is [1, 32, 1184, 896], repeat the image across a new dimension and adjust the batch dimension
image_tensor = image_tensor.unsqueeze(0)  # Add a batch dimension [1, 1, 1184, 896]
image_tensor = image_tensor.repeat(1, 32, 1, 1)  # Repeat the image to simulate 32 channels [1, 32, 1184, 896]

# Check the shape
print("Shape of the tensor:", image_tensor.shape)

import math

def psnr(target, output, max_pixel=1.0):
    mse = torch.mean((target - output) ** 2)
    if mse == 0:
        return float('inf')  # Infinite PSNR means no error.
    return 20 * math.log10(max_pixel / math.sqrt(mse))

def save_final_image(tensor, file_name="/content/final_image.png"):
    # Convert the tensor to a NumPy array
    np_image = torch_to_np(tensor)

    # Clip values to ensure they are within [0, 1]
    np_image = np.clip(np_image, 0, 1)

    # Convert from (C, H, W) to (H, W, C) if necessary
    if np_image.shape[0] == 3:
        np_image = np.transpose(np_image, (1, 2, 0))

    # Convert to an image and save
    im = Image.fromarray((np_image * 255).astype(np.uint8))
    im.save(file_name)
    #print(f"Image saved as {file_name}")


def closure():
    global i, output_tensor

    out_HR = net(image_tensor) #image_tensor for the actual compressed image as the target #net_input for uniform random noise.
    out_LR = downsampler(out_HR)

    total_loss = mse(out_LR, result_tensor)

    if tv_weight > 0:
        total_loss += tv_weight * tv_loss(out_HR)

    total_loss.backward()

    # Log
    psnr_log = psnr(result_tensor, out_LR)

    # History
    psnr_history.append((i,psnr_log))
    total_loss_history.append((i,total_loss.item()))

    if PLOT and i % 1 == 0:
        out_HR_np = torch_to_np(out_HR)
        # if i % 100 == 0:
        #     plot_image_grid([imgs['HR_np'], np.clip(out_HR_np, 0, 1)], factor=5, nrow=2)
        print(f"Iteration {i}: Loss {total_loss.item()} PSNR: {psnr_log} dB")

    # Save image at each iteration
    # Create 'output images' directory if it doesn't exist
    os.makedirs('/content/output_images', exist_ok=True)
    save_final_image(out_HR, f"output_images/i={i}.png")

    # Increment iteration counter
    i += 1

    # Save final image after the last iteration
    # if i == num_iter:
    #     save_final_image(out_HR, "final_output_image.png")
    # return total_loss

    return psnr_log

psnr_history = []
total_loss_history = []
i = 0
p = get_params(OPT_OVER, net, image_tensor)
optimize(OPTIMIZER, p, closure, LR, num_iter)

# Display the results
def plot_images(hr_image, output_image):
    plt.figure(figsize=(18, 6))
    titles = ['High-Resolution', 'Output']
    images = [hr_image, output_image]
    for i, (img, title) in enumerate(zip(images, titles)):
        plt.subplot(1, 2, i + 1)
        plt.imshow(img)
        plt.title(title)
        plt.axis('off')
    plt.show()

# out_HR_np = np.clip(torch_to_np(net(net_input)), 0, 1)
in_HR_np = imgs['HR_np']

# plot_images(out_HR_np, in_HR_np)

import matplotlib.pyplot as plt

# Extract iteration numbers and PSNR values
iterations, psnrs = zip(*psnr_history)

# Extract iteration numbers and Loss values
iterations_loss, losses = zip(*total_loss_history)

# Create a figure with dimensions suitable for IEEE two-column format
# IEEE two-column width is approximately 3.5 inches (8.9 cm)
fig_width = 3.5  # Width in inches
fig_height = fig_width * 0.75  # Adjust height to maintain aspect ratio

plt.rcParams.update({'font.size': 8})  # Set global font size

fig, ax1 = plt.subplots(figsize=(fig_width, fig_height))

# Plot PSNR on the first y-axis
color_psnr = 'tab:blue'
ax1.set_xlabel('Iteration', fontsize=8)
ax1.set_ylabel('PSNR (dB)', color=color_psnr, fontsize=8)
ax1.plot(iterations, psnrs, color=color_psnr, label='PSNR')
ax1.tick_params(axis='y', labelcolor=color_psnr)
ax1.tick_params(axis='both', which='major', labelsize=8)
ax1.grid(True, which='both', linestyle='--', linewidth=0.5)

# Create a second y-axis for Loss
ax2 = ax1.twinx()
color_loss = 'tab:red'
ax2.set_ylabel('Loss', color=color_loss, fontsize=8)
ax2.plot(iterations_loss, losses, color=color_loss, label='Loss')
ax2.tick_params(axis='y', labelcolor=color_loss)
ax2.tick_params(axis='both', which='major', labelsize=8)

# Combine legends from both axes
lines_1, labels_1 = ax1.get_legend_handles_labels()
lines_2, labels_2 = ax2.get_legend_handles_labels()
ax1.legend(lines_1 + lines_2, labels_1 + labels_2, loc='center right', fontsize=8)

# Adjust layout to prevent clipping
fig.tight_layout()

# Save the figure in high-resolution suitable for publication
plt.savefig('psnr_loss_plot.png', dpi=600, bbox_inches='tight')

# Show plot
plt.show()

# 1) Save only the state_dict (just the parameters)
torch.save(net.state_dict(), "hist_dip_model.pth")

# # OR 2) Save a checkpoint with more info (e.g. to store hyperparameters too)
# torch.save({
#     'model_state_dict': net.state_dict(),
#     'input_depth': input_depth,
#     'other_params': {
#         'skip_n33d': 128,
#         'skip_n33u': 128,
#         'num_scales': 5,
#         # etc. if you want to store them
#     }
# }, "hist_dip_checkpoint.pth")

"""# ***Validation Experiments***"""

from google.colab import files
import shutil

# Zip the output_images folder
shutil.make_archive('output_images', 'zip', '/content/output_images')

# Download the zipped folder
files.download('output_images.zip')

"""**Validating the model on new corrupted images from the SBMI**"""

img_test = load_LR_HR_imgs_sr('/content/validation_images/a.jpg', imsize, factor, enforse_div32)
(896, 1184)

from PIL import Image
image = Image.open('/content/validation_images/a.jpg').convert("L")  # Convert to grayscale if necessary
print(f"Original image size: {image.size}")


# Define the transformation
transform = transforms.Compose([
    transforms.Resize((1184, 896)),  # Resize the image ((1184, 896))
    transforms.ToTensor()            # Convert the image to a tensor for the given model
])

# Apply the transformation
test_new_tensor = transform(image)
test_new_tensor = test_new_tensor.to(device)
# Since the required shape is [1, 32, 1184, 896], repeat the image across a new dimension and adjust the batch dimension
test_new_tensor = test_new_tensor.unsqueeze(0)  # Add a batch dimension [1, 1, 1184, 896]
test_new_tensor = test_new_tensor.repeat(1, 32, 1, 1)
print(test_new_tensor.shape)

new_HR_np = torch_to_np(net(test_new_tensor))

# display(img_test['LR_pil'])
plot_image_grid([new_HR_np], factor=4, nrow=1);
# plot_image_grid([img_test['LR_np'], np.clip(new_HR_np, 0, 1)], factor=5, nrow=2)

import os
import torch
import torchvision.transforms as transforms
from PIL import Image

# Directory containing images to process
input_dir = "/content/validation_images"
# Directory to save processed images
output_dir = "/content/validation_images_processed"
os.makedirs(output_dir, exist_ok=True)

# Define any transform you need:
transform = transforms.Compose([
    transforms.Resize((1184, 896)),
    transforms.ToTensor()
])

# Ensure your model is on the correct device and in eval mode
net.eval()

# Loop through all files in the input directory
for file_name in os.listdir(input_dir):
    # Check if the file is an image by extension
    if file_name.lower().endswith((".jpg", ".jpeg", ".png", ".tif", ".bmp")):
        image_path = os.path.join(input_dir, file_name)

        # Load the image in grayscale, if desired
        img = Image.open(image_path).convert("L")

        # Apply transformations
        img_tensor = transform(img).to(device)  # e.g. 'cuda' or 'cpu'
        # Unsqueeze and repeat to get [1, 32, H, W]
        img_tensor = img_tensor.unsqueeze(0).repeat(1, 32, 1, 1)

        # Run through the network
        with torch.no_grad():  # No need to track gradients
            output_tensor = net(img_tensor)

        # Convert output tensor to NumPy and save
        output_np = torch_to_np(output_tensor)

        # Clip values to [0,1], transpose if necessary
        import numpy as np
        output_np = np.clip(output_np, 0, 1)
        if output_np.shape[0] == 3:  # [C,H,W] -> [H,W,C]
            output_np = np.transpose(output_np, (1, 2, 0))

        # Convert to PIL and save
        output_img = Image.fromarray((output_np * 255).astype(np.uint8))
        output_img.save(os.path.join(output_dir, f"processed_{file_name}"))

print("All images processed and saved.")

import shutil
from google.colab import files

# Path to your folder
folder_path = '/content/validation_images_processed'

# Create a ZIP archive of that folder
shutil.make_archive('validation_images_processed', 'zip', folder_path)

# Download the ZIP file
files.download('validation_images_processed.zip')

# Code cell: Create ground-truth images by applying per-image thresholds

import os
import cv2
import torch
import numpy as np
from PIL import Image
from torchvision.transforms import ToTensor, ToPILImage

# Dictionary mapping each filename to its threshold
thresholds = {
    'a.jpg': 125,
    'b.jpg': 152,
    'c.jpg': 50,
    'd.jpg': 143,
    'e.jpg': 62,
    'f.jpg': 75,
    'g.jpg': 150,
    'h.jpg': 59,
    'i.jpg': 80,
    'j.jpg': 148
}

# Input directory (where 'a.jpg', 'b.jpg', etc. are located)
input_dir = '/content/validation_images'
# Output directory for ground-truth images
gt_dir = '/content/ground_truth_images'
os.makedirs(gt_dir, exist_ok=True)

for filename, threshold_value in thresholds.items():
    image_path = os.path.join(input_dir, filename)

    # 1. Load image in grayscale for thresholding
    img_gray = cv2.imread(image_path, 0)
    if img_gray is None:
        print(f"Skipping {filename}: could not load or not an image.")
        continue

    # 2. Apply threshold to create a binary mask
    _, mask_array = cv2.threshold(img_gray, threshold_value, 255, cv2.THRESH_BINARY)

    # 3. Load original in color (RGB)
    img_color = Image.open(image_path).convert('RGB')

    # 4. Convert both to tensors
    mask_pil = Image.fromarray(mask_array).convert('RGB')
    if img_color.size != mask_pil.size:
        mask_pil = mask_pil.resize(img_color.size, Image.BICUBIC)

    tensor_color = ToTensor()(img_color)   # [C,H,W], range [0..1]
    tensor_mask  = ToTensor()(mask_pil)    # [C,H,W], range [0..1]

    # 5. Multiply (mask) the color image
    masked_tensor = tensor_color * tensor_mask  # element-wise multiplication

    # 6. Convert back to PIL and save
    masked_pil = ToPILImage()(masked_tensor)
    out_path = os.path.join(gt_dir, f"masked_{filename}")
    masked_pil.save(out_path)

    print(f"Created ground-truth image for '{filename}' at threshold={threshold_value}, saved to: {out_path}")

import os
import numpy as np
from PIL import Image
from torchvision.transforms import ToTensor
from skimage.metrics import structural_similarity as ssim

def compute_ssim(img1, img2):
    """
    Compute SSIM between two images.
    Both images should be NumPy arrays in the range [0,1].
    """
    # Convert images to grayscale if needed
    if img1.ndim == 3:
        img1 = np.dot(img1[..., :3], [0.2989, 0.5870, 0.1140])  # Convert RGB to grayscale
    if img2.ndim == 3:
        img2 = np.dot(img2[..., :3], [0.2989, 0.5870, 0.1140])  # Convert RGB to grayscale

    # Compute SSIM
    return ssim(img1, img2, data_range=1.0)

# **Set Paths for Different Image Sources**
validation_dir = "validation_images"   # Before images
gaussian_dir = "gaussian_images"       # Gaussian filtered images
processed_dir = "validation_images_processed"  # HIST-DIP processed images
gt_dir = "ground_truth_images"         # Ground-truth images

# Store SSIM results
ssim_results = []

# Loop through all ground-truth files starting with "masked_"
for gt_file in os.listdir(gt_dir):
    if gt_file.lower().startswith("masked_"):
        base_filename = gt_file[len("masked_"):]  # Extract base filename (e.g., "a.jpg")
        gt_path = os.path.join(gt_dir, gt_file)

        # Determine the reference image size from HIST-DIP processed images
        hist_dip_path = os.path.join(processed_dir, f"processed_{base_filename}")
        if not os.path.isfile(hist_dip_path):
            print(f"Skipping {base_filename}: No HIST-DIP file found.")
            continue

        # Load the HIST-DIP processed image and get its size
        hist_dip_img = Image.open(hist_dip_path).convert("RGB")
        ref_size = hist_dip_img.size  # Get (width, height) of the processed image

        # Load ground-truth image and resize to match HIST-DIP processed image
        img_gt = Image.open(gt_path).convert("RGB").resize(ref_size, Image.BICUBIC)
        tensor_gt = np.array(img_gt) / 255.0  # Normalize to [0,1]

        # Dictionary to hold images from different methods
        methods = {
            "Before": os.path.join(validation_dir, base_filename),
            "Gaussian": os.path.join(gaussian_dir, f"11x11_5_4_5_{base_filename}"),
            "HIST-DIP": hist_dip_path  # Already loaded, so no need to check again
        }

        for method, img_path in methods.items():
            if not os.path.isfile(img_path):
                print(f"Skipping {base_filename}: No {method} file found.")
                continue

            # Load and resize image to match HIST-DIP size
            img_proc = Image.open(img_path).convert("RGB").resize(ref_size, Image.BICUBIC)
            tensor_proc = np.array(img_proc) / 255.0  # Normalize to [0,1]

            # Compute SSIM
            ssim_val = compute_ssim(tensor_proc, tensor_gt)
            ssim_results.append((base_filename, method, ssim_val))
            print(f"SSIM({base_filename}, {method}) = {ssim_val:.4f}")

# Print final results
print("\nFinal SSIM Results:")
for filename, method, score in ssim_results:
    print(f"{filename} ({method}): {score:.4f}")

# Re-import necessary libraries due to execution state reset
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# SSIM results extracted from the image
data = {
    "Image": ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"],
    "Before": [0.0717, 0.0058, 0.0446, 0.0122, 0.0520, 0.0210, 0.0128, 0.0591, 0.0377, 0.0129],
    "Gaussian": [0.1439, 0.0475, 0.1998, 0.1919, 0.1137, 0.1192, 0.1531, 0.1105, 0.0875, 0.1985],
    "HIST-DIP": [0.8156, 0.8616, 0.7786, 0.8721, 0.7863, 0.8464, 0.8778, 0.7769, 0.8004, 0.8442],
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Plot the SSIM values
plt.figure(figsize=(10, 6))
x = np.arange(len(df["Image"]))

plt.bar(x - 0.2, df["Before"], width=0.2, label="Before", color="orange")
plt.bar(x, df["Gaussian"], width=0.2, label="Gaussian", color="blue")
plt.bar(x + 0.2, df["HIST-DIP"], width=0.2, label="HIST-DIP", color="green")

plt.xlabel("Image")
plt.ylabel("SSIM Score")
plt.title("Comparison of SSIM Across Different Methods")
plt.xticks(x, df["Image"])
plt.legend()
plt.ylim(0, 1)  # SSIM values range from 0 to 1

# Show the plot
plt.show()

import os
import numpy as np
from PIL import Image
from skimage.metrics import structural_similarity as ssim

# Allow large images to be processed
Image.MAX_IMAGE_PIXELS = None

# Define paths
validation_image_path = "/content/validation_images/a.jpg"
ground_truth_image_path = "/content/ground_truth_images/masked_a.jpg"

def compute_ssim(image_path1, image_path2):
    """
    Compute SSIM between two images after ensuring they have the same size.
    Fixes issues with large images and ensures correct format.
    """
    # Load images
    img1 = Image.open(image_path1).convert("RGB")  # Ensure 3-channel format
    img2 = Image.open(image_path2).convert("RGB")

    # Resize second image to match first image's size if necessary
    if img1.size != img2.size:
        img2 = img2.resize(img1.size, Image.BICUBIC)

    # Convert to NumPy arrays (uint8 type)
    img1_np = np.array(img1, dtype=np.uint8)
    img2_np = np.array(img2, dtype=np.uint8)

    # Ensure the images have at least 7x7 size for SSIM
    min_size = min(img1_np.shape[0], img1_np.shape[1])
    win_size = min(7, min_size)  # Set win_size to the minimum possible valid value

    # Compute SSIM (for RGB images, set channel_axis=2)
    ssim_value = ssim(img1_np, img2_np,
                      win_size=win_size,
                      channel_axis=2,
                      data_range=255)

    return ssim_value

# Compute SSIM between a.jpg and masked_a.jpg
ssim_score = compute_ssim(validation_image_path, ground_truth_image_path)
print(f"SSIM between 'a.jpg' and 'masked_a.jpg': {ssim_score:.4f}")

import os
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from torchvision.transforms import ToTensor
from skimage.metrics import structural_similarity as ssim

# Set device to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

def compute_ssim(tensor1, tensor2):
    """
    Compute SSIM between two PyTorch tensors: shape [C, H, W].
    Moves computation to the GPU for efficiency.
    """
    img1_np = tensor1.squeeze().cpu().numpy().transpose(1, 2, 0)
    img2_np = tensor2.squeeze().cpu().numpy().transpose(1, 2, 0)

    # Convert to grayscale if needed
    if img1_np.shape[-1] == 3:
        img1_np = np.dot(img1_np[..., :3], [0.2989, 0.5870, 0.1140])
        img2_np = np.dot(img2_np[..., :3], [0.2989, 0.5870, 0.1140])

    return ssim(img1_np, img2_np, data_range=1.0)

# Image directories
image_dirs = {
     "Before": "/content/validation_images"
    # ,"Gaussian": "/content/gaussian_images",
    # "HIST-DIP": "/content/validation_images_processed"
}
gt_dir = "/content/ground_truth_images"

# Store SSIM results
ssim_results = {"Before": [], "Gaussian": [], "HIST-DIP": []}

# Load and process images on GPU
for gt_file in os.listdir(gt_dir):
    if gt_file.lower().startswith("masked_"):
        base_filename = gt_file[len("masked_"):]  # Extract base filename
        gt_path = os.path.join(gt_dir, gt_file)

        # Load and move ground-truth image to GPU
        img_gt = Image.open(gt_path).convert("RGB")
        tensor_gt = ToTensor()(img_gt).to(device)

        for method, img_dir in image_dirs.items():
            proc_filename = (
                f"11x11_5_4_5_{base_filename}" if method == "Gaussian"
                else f"processed_{base_filename}" if method == "HIST-DIP"
                else base_filename
            )

            proc_path = os.path.join(img_dir, proc_filename)
            if not os.path.isfile(proc_path):
                print(f"Missing {method} file for {gt_file}, skipping.")
                continue

            # Load and move processed image to GPU
            img_proc = Image.open(proc_path).convert("RGB")
            tensor_proc = ToTensor()(img_proc).to(device)

            # Resize GT image if necessary
            if img_gt.size != img_proc.size:
                img_gt = img_gt.resize(img_proc.size, Image.BICUBIC)
                tensor_gt = ToTensor()(img_gt).to(device)

            # Compute SSIM on GPU
            ssim_val = compute_ssim(tensor_proc, tensor_gt)
            ssim_results[method].append(ssim_val)
            print(f"SSIM({base_filename}, {method}) = {ssim_val:.4f}")

# Convert results to NumPy arrays for plotting
methods = ["Before", "Gaussian", "HIST-DIP"]
means = [np.mean(ssim_results[m]) for m in methods]
std_devs = [np.std(ssim_results[m]) for m in methods]

# Plot SSIM Comparison (GPU Accelerated)
plt.figure(figsize=(8, 5))
plt.bar(methods, means, yerr=std_devs, capsize=5, color=["orange", "red", "green"])
plt.xlabel("Method")
plt.ylabel("SSIM")
plt.title("Comparison of SSIM Across Different Methods (GPU Optimized)")
plt.ylim(0, 1)
plt.grid(axis="y", linestyle="--", alpha=0.7)
plt.show()

import os
import torch
import numpy as np
from PIL import Image
from torchvision.transforms import ToTensor
from skimage.metrics import structural_similarity as ssim

def compute_ssim(tensor1, tensor2):
    """
    Compute SSIM between two PyTorch tensors: shape [C, H, W] or [1, C, H, W].
    Returns SSIM score.
    """
    # Convert tensors to NumPy arrays (ensure they are in [0,1] range)
    img1_np = tensor1.squeeze().cpu().numpy().transpose(1, 2, 0)
    img2_np = tensor2.squeeze().cpu().numpy().transpose(1, 2, 0)

    # Convert to grayscale if needed (SSIM requires 2D for single-channel)
    if img1_np.shape[-1] == 3:
        img1_np = np.dot(img1_np[..., :3], [0.2989, 0.5870, 0.1140])  # Convert to grayscale
        img2_np = np.dot(img2_np[..., :3], [0.2989, 0.5870, 0.1140])  # Convert to grayscale

    # Compute SSIM
    return ssim(img1_np, img2_np, data_range=1.0)

# **Set Paths for Before, Gaussian, DIP-Processed, and Ground Truth Images**
image_dirs = {
    "Before": "/content/validation_images"
    # ,"Gaussian": "/content/gaussian_images"
    # ,"DIP": "/content/validation_images_processed"
}
gt_dir = "/content/ground_truth_images"

# Store SSIM values for comparison
ssim_results = []

# Loop through all ground-truth files starting with "masked_"
for gt_file in os.listdir(gt_dir):
    if gt_file.lower().startswith("masked_"):
        base_filename = gt_file[len("masked_"):]  # Extract the base filename (e.g., "a.jpg")
        gt_path = os.path.join(gt_dir, gt_file)

        # Load ground-truth image
        img_gt = Image.open(gt_path).convert("RGB")
        tensor_gt = ToTensor()(img_gt)

        for method, img_dir in image_dirs.items():
            # Construct the filename based on method
            if method == "Gaussian":
                proc_filename = f"11x11_5_4_5_{base_filename}"
            elif method == "DIP":
                proc_filename = f"processed_{base_filename}"
            else:
                proc_filename = base_filename  # Before image

            proc_path = os.path.join(img_dir, proc_filename)

            # Check if image exists
            if not os.path.isfile(proc_path):
                print(f"No {method} file found for {gt_file}, skipping.")
                continue

            # Load image
            img_proc = Image.open(proc_path).convert("RGB")
            tensor_proc = ToTensor()(img_proc)

            # Resize GT image if necessary
            if img_gt.size != img_proc.size:
                img_gt = img_gt.resize(img_proc.size, Image.BICUBIC)
                tensor_gt = ToTensor()(img_gt)

            # Check shape mismatch
            if tensor_proc.shape != tensor_gt.shape:
                print(f"Shape mismatch: {proc_filename} vs {gt_file}, skipping.")
                continue

            # Compute SSIM
            ssim_val = compute_ssim(tensor_proc, tensor_gt)
            ssim_results.append([base_filename, method, ssim_val])
            print(f"SSIM({base_filename}, {method}) = {ssim_val:.4f}")

import os
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from torchvision.transforms import ToTensor
from skimage.metrics import structural_similarity as ssim

def compute_ssim(tensor1, tensor2):
    """
    Compute SSIM between two PyTorch tensors: shape [C, H, W].
    Returns SSIM score.
    """
    img1_np = tensor1.squeeze().gpu().numpy().transpose(1, 2, 0)
    img2_np = tensor2.squeeze().gpu().numpy().transpose(1, 2, 0)

    # Convert to grayscale if necessary
    if img1_np.shape[-1] == 3:
        img1_np = np.dot(img1_np[..., :3], [0.2989, 0.5870, 0.1140])
        img2_np = np.dot(img2_np[..., :3], [0.2989, 0.5870, 0.1140])

    return ssim(img1_np, img2_np, data_range=1.0)

# Directories containing images
image_dirs = {
    "Before": "/content/validation_images",
    "Gaussian": "/content/gaussian_images",
    "HIST-DIP": "/content/validation_images_processed"
}
gt_dir = "/content/ground_truth_images"

# Store SSIM values
ssim_results = {"Before": [], "Gaussian": [], "HIST-DIP": []}

# Iterate over ground-truth images
for gt_file in os.listdir(gt_dir):
    if gt_file.lower().startswith("masked_"):
        base_filename = gt_file[len("masked_"):]  # Extract original filename
        gt_path = os.path.join(gt_dir, gt_file)

        # Load ground-truth image
        img_gt = Image.open(gt_path).convert("RGB")
        tensor_gt = ToTensor()(img_gt)

        for method, img_dir in image_dirs.items():
            if method == "Gaussian":
                proc_filename = f"11x11_5_4_5_{base_filename}"
            elif method == "HIST-DIP":
                proc_filename = f"processed_{base_filename}"
            else:
                proc_filename = base_filename  # Before image

            proc_path = os.path.join(img_dir, proc_filename)

            if not os.path.isfile(proc_path):
                print(f"Missing {method} file for {gt_file}, skipping.")
                continue

            # Load processed image
            img_proc = Image.open(proc_path).convert("RGB")
            tensor_proc = ToTensor()(img_proc)

            # Resize GT image if needed
            if img_gt.size != img_proc.size:
                img_gt = img_gt.resize(img_proc.size, Image.BICUBIC)
                tensor_gt = ToTensor()(img_gt)

            # Compute SSIM
            ssim_val = compute_ssim(tensor_proc, tensor_gt)
            ssim_results[method].append(ssim_val)
            print(f"SSIM({base_filename}, {method}) = {ssim_val:.4f}")

# Convert results to NumPy arrays for plotting
methods = ["Before", "Gaussian", "HIST-DIP"]
means = [np.mean(ssim_results[m]) for m in methods]
std_devs = [np.std(ssim_results[m]) for m in methods]

# Plot SSIM Comparison
plt.figure(figsize=(8, 5))
plt.bar(methods, means, yerr=std_devs, capsize=5, color=["orange", "red", "green"])
plt.xlabel("Method")
plt.ylabel("SSIM")
plt.title("Comparison of SSIM Across Different Methods")
plt.ylim(0, 1)  # SSIM range is [0,1]
plt.grid(axis="y", linestyle="--", alpha=0.7)
plt.show()

import os
import math
import numpy as np
import torch
from PIL import Image
from torchvision.transforms import ToTensor

def psnr(tensor1, tensor2, max_val=1.0):
    """
    Compute PSNR between two PyTorch tensors: shape [C, H, W] or [1, C, H, W].
    Returns PSNR in decibels (dB).
    """
    # Remove batch dimension if present
    if tensor1.dim() == 4 and tensor1.size(0) == 1:
        tensor1 = tensor1.squeeze(0)
    if tensor2.dim() == 4 and tensor2.size(0) == 1:
        tensor2 = tensor2.squeeze(0)

    if tensor1.shape != tensor2.shape:
        raise ValueError(f"Shape mismatch: {tensor1.shape} vs {tensor2.shape}")

    mse_val = torch.mean((tensor1 - tensor2) ** 2).item()
    if mse_val == 0:
        return float('inf')

    return 20 * math.log10(max_val / math.sqrt(mse_val))

# Paths for validation set and ground truth images
validation_dir = "/content/validation_images"
ground_truth_dir = "/content/ground_truth_images"

# Collect all ground-truth filenames that start with "masked_"
for gt_file in os.listdir(ground_truth_dir):
    if gt_file.lower().startswith("masked_"):
        # The original filename is gt_file without "masked_" prefix
        original_filename = gt_file[len("masked_"):]
        gt_path = os.path.join(ground_truth_dir, gt_file)
        original_path = os.path.join(validation_dir, original_filename)

        # Make sure the original file actually exists
        if not os.path.isfile(original_path):
            print(f"Skipping {gt_file}: no matching original found for {original_filename}")
            continue

        # 1. Load both images in color (or grayscale if you prefer)
        img_original = Image.open(original_path).convert('RGB')
        img_masked   = Image.open(gt_path).convert('RGB')

        # 2. Convert each to a PyTorch tensor in [0..1]
        tensor_original = ToTensor()(img_original)  # [C,H,W]
        tensor_masked   = ToTensor()(img_masked)    # [C,H,W]

        # 3. Check shape mismatch or forcibly resize
        if tensor_original.shape != tensor_masked.shape:
            # Option A: Raise an error
            # raise ValueError(f"Shape mismatch for {gt_file} vs. original {original_filename}")

            # Option B: Automatically resize the masked image to match
            # (Uncomment if you'd prefer resizing to skipping or error)
            # c,h,w = tensor_original.shape
            # img_masked = img_masked.resize(img_original.size, Image.BICUBIC)
            # tensor_masked = ToTensor()(img_masked)

            # For now, we'll just do:
            print(f"Shape mismatch for {gt_file}, skipping.")
            continue

        # 4. Compute PSNR
        value_psnr = psnr(tensor_original, tensor_masked, max_val=1.0)

        # 5. Print result
        print(f"PSNR({original_filename}, {gt_file}) = {value_psnr:.2f} dB")

import os
import math
import torch
from PIL import Image
import numpy as np
from torchvision.transforms import ToTensor

def psnr(tensor1, tensor2, max_val=1.0):
    """
    Compute PSNR between two PyTorch tensors: shape [C, H, W] or [1, C, H, W].
    Returns PSNR in decibels (dB).
    """
    # Remove batch dimension if present
    if tensor1.dim() == 4 and tensor1.size(0) == 1:
        tensor1 = tensor1.squeeze(0)
    if tensor2.dim() == 4 and tensor2.size(0) == 1:
        tensor2 = tensor2.squeeze(0)

    if tensor1.shape != tensor2.shape:
        raise ValueError(f"Shape mismatch even after resizing: {tensor1.shape} vs {tensor2.shape}")

    mse_val = torch.mean((tensor1 - tensor2) ** 2).item()
    if mse_val == 0:
        return float('inf')

    return 20 * math.log10(max_val / math.sqrt(mse_val))

# Paths for the DIP-processed images and the ground-truth images
processed_dir = "/content/validation_images_processed"
gt_dir = "/content/ground_truth_images"

# Loop through all processed files that start with "processed_"
for proc_file in os.listdir(processed_dir):
    if proc_file.lower().startswith("processed_"):
        # The original base filename is everything after "processed_"
        base_filename = proc_file[len("processed_"):]  # e.g., "a.jpg"

        proc_path = os.path.join(processed_dir, proc_file)
        gt_filename = f"masked_{base_filename}"       # e.g., "masked_a.jpg"
        gt_path = os.path.join(gt_dir, gt_filename)

        # Check if the ground-truth file exists
        if not os.path.isfile(gt_path):
            print(f"No ground-truth file found for {proc_file} (expected {gt_filename}), skipping.")
            continue

        # Load both images in a consistent color mode
        img_proc = Image.open(proc_path).convert("RGB")
        img_gt   = Image.open(gt_path).convert("RGB")

        # 1) Convert DIP-processed image to a tensor
        tensor_proc = ToTensor()(img_proc)

        # 2) If shapes differ, forcibly resize the GT image
        #    (We compare PIL image sizes first because shape mismatch in torch
        #     means the pixel dimensions differ.)
        if img_gt.size != img_proc.size:
            # print(f"Resizing ground truth from {img_gt.size} to {img_proc.size} for {gt_filename}")
            # Resize ground-truth to the processed image's size
            img_gt = img_gt.resize(img_proc.size, Image.BICUBIC)

        # Now convert the (possibly resized) GT image to a tensor
        tensor_gt = ToTensor()(img_gt)

        # After resizing, we check one more time for shape mismatch
        if tensor_proc.shape != tensor_gt.shape:
            print(f"Shape mismatch even after resizing: {proc_file} vs {gt_filename}, skipping.")
            continue

        # Compute PSNR
        psnr_val = psnr(tensor_proc, tensor_gt, max_val=1.0)
        print(f"PSNR({proc_file}, {gt_filename}) = {psnr_val:.2f} dB")

# Paths for the DIP-processed images and the ground-truth images
processed_dir = "/content/gaussian_images"
gt_dir = "/content/ground_truth_images"

# Loop through all processed files that start with "processed_"
for proc_file in os.listdir(processed_dir):
    if proc_file.lower().startswith("11x11_5_4_5_"):
        # The original base filename is everything after "processed_"
        base_filename = proc_file[len("11x11_5_4_5_"):]  # e.g., "a.jpg"

        proc_path = os.path.join(processed_dir, proc_file)
        gt_filename = f"masked_{base_filename}"       # e.g., "masked_a.jpg"
        gt_path = os.path.join(gt_dir, gt_filename)

        # Check if the ground-truth file exists
        if not os.path.isfile(gt_path):
            print(f"No ground-truth file found for {proc_file} (expected {gt_filename}), skipping.")
            continue

        # Load both images in a consistent color mode
        img_proc = Image.open(proc_path).convert("RGB")
        img_gt   = Image.open(gt_path).convert("RGB")

        # 1) Convert DIP-processed image to a tensor
        tensor_proc = ToTensor()(img_proc)

        # 2) If shapes differ, forcibly resize the GT image
        #    (We compare PIL image sizes first because shape mismatch in torch
        #     means the pixel dimensions differ.)
        if img_gt.size != img_proc.size:
            # print(f"Resizing ground truth from {img_gt.size} to {img_proc.size} for {gt_filename}")
            # Resize ground-truth to the processed image's size
            img_gt = img_gt.resize(img_proc.size, Image.BICUBIC)

        # Now convert the (possibly resized) GT image to a tensor
        tensor_gt = ToTensor()(img_gt)

        # After resizing, we check one more time for shape mismatch
        if tensor_proc.shape != tensor_gt.shape:
            print(f"Shape mismatch even after resizing: {proc_file} vs {gt_filename}, skipping.")
            continue

        # Compute PSNR
        psnr_val = psnr(tensor_proc, tensor_gt, max_val=1.0)
        print(f"PSNR({proc_file}, {gt_filename}) = {psnr_val:.2f} dB")

import shutil
from google.colab import files

# Path to your folder
folder_path = '/content/ground_truth_images'

# Create a ZIP archive of that folder
shutil.make_archive('ground_truth_images', 'zip', folder_path)

# Download the ZIP file
files.download('ground_truth_images.zip')

"""# WEB Application part of the project https://denoisedip.vercel.app/


"""

import torch
import torch.nn as nn
from PIL import Image
import torchvision.transforms as transforms

# -----------------------------------------
# 1) Paste or import your DIP code here
#    (the 'skip' module, 'get_net' etc.)
#    For example:

def skip( ... ):
    # same code from your notebook
    pass

def get_net(input_depth, NET_TYPE='skip', pad='reflection',
            skip_n33d=128, skip_n33u=128, skip_n11=4, num_scales=5,
            upsample_mode='bilinear'):
    # same code from your notebook to build 'net'
    pass
# -----------------------------------------

def load_dip_model(model_path="hist_dip_model.pth",
                   input_depth=32):
    """
    Loads the DIP model architecture and its saved weights.
    """
    # Instantiate the architecture
    net = get_net(
        input_depth=input_depth,
        NET_TYPE='skip',
        pad='reflection',
        skip_n33d=128,
        skip_n33u=128,
        skip_n11=4,
        num_scales=5,
        upsample_mode='bilinear'
    )

    # Load the weights
    net.load_state_dict(torch.load(model_path, map_location='cpu'))
    net.eval()  # Set to inference mode
    return net

import torch
import torch.nn as nn

class Concat(nn.Module):
    """Concatenation module to combine outputs along a given dimension."""
    def __init__(self, dim, *modules):
        super(Concat, self).__init__()
        self.dim = dim
        # Add each module as a submodule of this module
        for idx, module in enumerate(modules):
            self.add_module(str(idx), module)
    def forward(self, x):
        # Forward input through all submodules and concatenate results
        outputs = [module(x) for module in self._modules.values()]
        if not outputs:
            return x
        # If spatial dimensions differ, crop to the smallest size before concatenation
        min_h = min(out.shape[2] for out in outputs)
        min_w = min(out.shape[3] for out in outputs)
        outputs = [out[:, :, :min_h, :min_w] for out in outputs]
        return torch.cat(outputs, dim=self.dim)

def act(act_fun='LeakyReLU'):
    """Return an activation function module given a name or module."""
    if isinstance(act_fun, str):
        act_fun = act_fun.lower()
        if act_fun == 'leakyrelu':
            return nn.LeakyReLU(0.2, inplace=True)
        elif act_fun == 'relu':
            return nn.ReLU(inplace=True)
        elif act_fun == 'elu':
            return nn.ELU(inplace=True)
        elif act_fun == 'swish':
            class Swish(nn.Module):
                def __init__(self):
                    super(Swish, self).__init__()
                    self.sig = nn.Sigmoid()
                def forward(self, x):
                    return x * self.sig(x)
            return Swish()
        elif act_fun == 'none':
            return nn.Identity()
        else:
            raise ValueError(f"Unknown activation function: {act_fun}")
    # If act_fun is already an nn.Module (or a class), return an instance or the module itself
    if isinstance(act_fun, type):
        return act_fun()
    return act_fun

def bn(num_features):
    """Return a 2D batch normalization layer."""
    return nn.BatchNorm2d(num_features)

def conv(in_f, out_f, kernel_size, stride=1, bias=True, pad='zero', downsample_mode='stride'):
    """
    Create a convolutional layer (with optional padding and downsampling).
    If pad='reflection', uses ReflectionPad2d. Otherwise uses zero-padding via Conv2d's padding.
    If downsample_mode is 'avg' or 'max' and stride > 1, applies pooling for downsampling.
    """
    # Padding setup
    padder = None
    pad_val = (kernel_size - 1) // 2  # half the kernel for symmetric padding
    if pad == 'reflection':
        if pad_val != 0:
            padder = nn.ReflectionPad2d(pad_val)
            pad_val = 0  # Conv will not handle padding if we explicitly pad
    # Downsampler setup (for stride > 1)
    downsampler = None
    if stride != 1 and downsample_mode != 'stride':
        if downsample_mode == 'avg':
            downsampler = nn.AvgPool2d(stride, stride)
        elif downsample_mode == 'max':
            downsampler = nn.MaxPool2d(stride, stride)
        else:
            raise ValueError(f"Unknown downsample_mode: {downsample_mode}")
        stride = 1  # use pooling instead of stride in conv
    # Convolutional layer
    conv_layer = nn.Conv2d(in_f, out_f, kernel_size, stride, padding=pad_val, bias=bias)
    # If we need padding or downsampling, wrap them in a Sequential
    if padder or downsampler:
        layers = []
        if padder:
            layers.append(padder)
        layers.append(conv_layer)
        if downsampler:
            layers.append(downsampler)
        return nn.Sequential(*layers)
    else:
        return conv_layer

def skip(num_input_channels=3, num_output_channels=3,
         num_channels_down=(128, 128, 128, 128, 128),
         num_channels_up=(128, 128, 128, 128, 128),
         num_channels_skip=(4, 4, 4, 4, 4),
         filter_size_down=3, filter_size_up=3, filter_skip_size=1,
         need_sigmoid=True, need_bias=True, pad='reflection',
         upsample_mode='nearest', downsample_mode='stride', act_fun='LeakyReLU',
         need1x1_up=True):
    """
    Assemble an encoder-decoder network with skip connections (Deep Image Prior 'skip' architecture).
    """
    # Ensure parameters are list/tuple
    n_scales = len(num_channels_down)
    assert n_scales == len(num_channels_up) == len(num_channels_skip), "Channel lists must have the same length"
    if not isinstance(filter_size_down, (list, tuple)):
        filter_size_down = [filter_size_down] * n_scales
    if not isinstance(filter_size_up, (list, tuple)):
        filter_size_up = [filter_size_up] * n_scales
    if not isinstance(upsample_mode, (list, tuple)):
        upsample_mode = [upsample_mode] * n_scales
    if not isinstance(downsample_mode, (list, tuple)):
        downsample_mode = [downsample_mode] * n_scales

    # Main model is a Sequential container
    model = nn.Sequential()
    # We'll build the U-Net like structure by iterating over scales
    input_depth = num_input_channels
    # Pointers for building nested module structure
    model_current = model  # current working Sequential to append to
    for scale in range(n_scales):
        # Create new sequential modules for deeper (downsampling path) and skip connection
        deeper_seq = nn.Sequential()
        skip_seq = nn.Sequential()
        # If skip connection channels > 0, add concatenation of skip and deeper
        if num_channels_skip[scale] != 0:
            model_current.add_module(f"concat_{scale}", Concat(dim=1, *[skip_seq, deeper_seq]))
        else:
            # No skip connection at this scale, add deeper_seq directly
            model_current.add_module(f"skip_none_{scale}", deeper_seq)
        # After combining skip and deeper, add batch norm
        out_channels = num_channels_skip[scale] + (num_channels_up[scale+1] if scale < n_scales-1 else num_channels_down[scale])
        model_current.add_module(f"bn_combo_{scale}", bn(out_channels))
        # Build skip connection branch (one conv + BN + activation if channels > 0)
        if num_channels_skip[scale] != 0:
            skip_seq.add_module(f"conv_skip_{scale}", conv(input_depth, num_channels_skip[scale],
                                                           filter_skip_size, stride=1,
                                                           bias=need_bias, pad=pad))
            skip_seq.add_module(f"bn_skip_{scale}", bn(num_channels_skip[scale]))
            skip_seq.add_module(f"act_skip_{scale}", act(act_fun))
        # Build deeper (encoder) branch with two convolutions and activations
        deeper_seq.add_module(f"conv_down_{scale}_0", conv(input_depth, num_channels_down[scale],
                                                           filter_size_down[scale], stride=2,
                                                           bias=need_bias, pad=pad, downsample_mode=downsample_mode[scale]))
        deeper_seq.add_module(f"bn_down_{scale}_0", bn(num_channels_down[scale]))
        deeper_seq.add_module(f"act_down_{scale}_0", act(act_fun))
        deeper_seq.add_module(f"conv_down_{scale}_1", conv(num_channels_down[scale], num_channels_down[scale],
                                                           filter_size_down[scale], stride=1,
                                                           bias=need_bias, pad=pad))
        deeper_seq.add_module(f"bn_down_{scale}_1", bn(num_channels_down[scale]))
        deeper_seq.add_module(f"act_down_{scale}_1", act(act_fun))
        # If not at the last scale, prepare for next nested block
        if scale < n_scales - 1:
            # Create a new deeper_main sequential to go down another level
            deeper_main = nn.Sequential()
            deeper_seq.add_module(f"deeper_{scale}", deeper_main)
            # After descending deeper, add upsampling to bring features back up
            deeper_seq.add_module(f"upsample_{scale}", nn.Upsample(scale_factor=2, mode=upsample_mode[scale]))
            # Build the upsampling (decoder) branch: one or two conv layers to combine skip and deeper features
            model_current.add_module(f"conv_up_{scale}_0", conv(num_channels_skip[scale] + num_channels_up[scale+1],
                                                                num_channels_up[scale], filter_size_up[scale],
                                                                stride=1, bias=need_bias, pad=pad))
            model_current.add_module(f"bn_up_{scale}_0", bn(num_channels_up[scale]))
            model_current.add_module(f"act_up_{scale}_0", act(act_fun))
            if need1x1_up:
                model_current.add_module(f"conv_up_{scale}_1", conv(num_channels_up[scale], num_channels_up[scale],
                                                                    kernel_size=1, stride=1, bias=need_bias, pad=pad))
                model_current.add_module(f"bn_up_{scale}_1", bn(num_channels_up[scale]))
                model_current.add_module(f"act_up_{scale}_1", act(act_fun))
            # Move the pointer to the next deeper level for the next iteration
            input_depth = num_channels_down[scale]  # update input depth for next scale
            model_current = deeper_main  # go one level deeper
        else:
            # Last scale: at the bottom of U-Net, just upsample back up after convs
            deeper_seq.add_module(f"upsample_{scale}", nn.Upsample(scale_factor=2, mode=upsample_mode[scale]))
            # Combine skip and deepest features on the way up
            model_current.add_module(f"conv_up_{scale}_0", conv(num_channels_skip[scale] + num_channels_down[scale],
                                                                num_channels_up[scale], filter_size_up[scale],
                                                                stride=1, bias=need_bias, pad=pad))
            model_current.add_module(f"bn_up_{scale}_0", bn(num_channels_up[scale]))
            model_current.add_module(f"act_up_{scale}_0", act(act_fun))
            if need1x1_up:
                model_current.add_module(f"conv_up_{scale}_1", conv(num_channels_up[scale], num_channels_up[scale],
                                                                    kernel_size=1, stride=1, bias=need_bias, pad=pad))
                model_current.add_module(f"bn_up_{scale}_1", bn(num_channels_up[scale]))
                model_current.add_module(f"act_up_{scale}_1", act(act_fun))
            # No deeper level to descend to, so no pointer update needed

    # Final output layer: 1x1 convolution to get desired output channels
    model.add_module("final_conv", conv(num_channels_up[0], num_output_channels, kernel_size=1,
                                       stride=1, bias=need_bias, pad=pad))
    if need_sigmoid:
        model.add_module("output_sigmoid", nn.Sigmoid())
    return model

def get_net(input_depth, NET_TYPE="skip", pad='reflection', upsample_mode='nearest',
            n_channels=3, skip_n33d=128, skip_n33u=128, skip_n11=4, num_scales=5):
    """
    Create a network of a given type with the specified parameters.
    NET_TYPE 'skip' yields the DIP skip network (U-Net with skip connections).
    """
    if NET_TYPE == 'skip':
        # Define channel counts for each scale based on given parameters
        num_channels_down = [skip_n33d] * num_scales
        num_channels_up   = [skip_n33u] * num_scales
        num_channels_skip = [skip_n11]  * num_scales
        # Assemble the skip network
        net = skip(num_input_channels=input_depth, num_output_channels=n_channels,
                   num_channels_down=num_channels_down, num_channels_up=num_channels_up,
                   num_channels_skip=num_channels_skip, filter_size_down=3, filter_size_up=3,
                   filter_skip_size=1, need_sigmoid=True, need_bias=True, pad=pad,
                   upsample_mode=upsample_mode, downsample_mode='stride',
                   act_fun='LeakyReLU', need1x1_up=True)
    else:
        raise ValueError(f"Unsupported NET_TYPE: {NET_TYPE}")
    return net

def load_dip_model(weights_path, map_location='cpu'):
    """
    Load a Deep Image Prior model from a checkpoint, ensuring it's on CPU.
    The checkpoint is expected to contain a state dict of the network.
    """
    # Load the saved state dict (force onto CPU)
    state = torch.load(weights_path, map_location=map_location)
    # Some DIP checkpoints might save a dict with 'net' key or full model; handle accordingly
    if isinstance(state, dict) and 'net' in state:
        state = state['net']
    # Build the DIP skip network architecture (using default DIP parameters)
    net = get_net(input_depth=32, NET_TYPE='skip', pad='reflection',
                  upsample_mode='nearest', n_channels=3,
                  skip_n33d=128, skip_n33u=128, skip_n11=4, num_scales=5)
    # Load the weights into the network
    net.load_state_dict(state)
    net.eval()  # Set in evaluation mode by default
    return net

pip install flask flask-cors torch torchvision pillow

from flask import Flask, request, jsonify, send_file
from PIL import Image
import io
import os
import numpy as np  # <-- MISSING: needed for np.clip, np.transpose, etc.
import torch
import torchvision.transforms as transforms
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

BASE_DIR = os.getcwd()  # ✅ works in notebooks

PROCESSED_IMAGE_PATH = os.path.join(BASE_DIR, "processed_images")
os.makedirs(PROCESSED_IMAGE_PATH, exist_ok=True)

# -------------------------
# Load your DIP model once at startup (recommended)
# -------------------------
# The below import must match the name of the Python file/module
# where you placed your DIP code (skip, get_net, load_dip_model, etc.).
# For example, if you saved it in 'dip_code.py', do:
#   from dip_code import load_dip_model
# Make sure the function signature also matches.
#
# In your snippet you have:
#   from your_dip_code import load_dip_model
# but that's presumably a placeholder.
#
# We assume you have a function signature like:
#   def load_dip_model(weights_path, map_location='cpu'):
#       ...
#   return net

# from your_dip_code import load_dip_model

# The code snippet references "model_path" and "input_depth=32"
# but your actual signature might differ, e.g. 'weights_path'
# instead of 'model_path'. Make sure you adapt accordingly.
#
# For example:
#   net = load_dip_model("hist_dip_model.pth", map_location='cpu')

net = load_dip_model("/content/hist_dip_model.pth")
print("DIP Model loaded.")

@app.route('/processImage', methods=['POST'])
def process_image():
    if 'image' not in request.files:
        return jsonify({'message': 'No image provided'}), 400

    image_file = request.files['image']
    original_filename = os.path.splitext(image_file.filename)[0]

    try:
        # 1) Load and transform image
        image = Image.open(image_file).convert("L")  # or "RGB" if you prefer color

        transform_pipeline = transforms.Compose([
            # Possibly do: transforms.Resize((1184, 896)),
            transforms.ToTensor()
        ])

        # shape => [1,1,H,W]
        img_tensor = transform_pipeline(image).unsqueeze(0)
        # DIP expects 32 input channels (based on your training), so repeat:
        # shape => [1,32,H,W]
        img_tensor = img_tensor.repeat(1, 32, 1, 1)

        # 2) Inference (no gradient)
        with torch.no_grad():
            output_tensor = net(img_tensor)

        # 3) Convert output to PIL
        # Suppose the DIP final layer is [1,3,H,W]
        output_np = output_tensor.squeeze(0).cpu().numpy()  # shape => [3,H,W]
        output_np = np.clip(output_np, 0, 1)
        output_np = (output_np * 255).astype(np.uint8)
        output_np = np.transpose(output_np, (1, 2, 0))  # => [H,W,3]

        out_img = Image.fromarray(output_np)

        # 4) Save locally
        output_filename = f"{original_filename}-output.png"
        image_path = os.path.join(PROCESSED_IMAGE_PATH, output_filename)
        out_img.save(image_path)

        return jsonify({
            'message': 'Image processed and saved successfully',
            'image_path': output_filename
        }), 200

    except Exception as e:
        return jsonify({
            'message': 'Error processing image',
            'error': str(e)
        }), 500

@app.route('/getProcessedImage', methods=['GET'])
def get_processed_image():
    try:
        image_name = request.args.get('imageName')
        if not image_name:
            return jsonify({'message': 'Image name is required'}), 400

        output_filename = f"{os.path.splitext(image_name)[0]}-output.png"
        image_path = os.path.join(PROCESSED_IMAGE_PATH, output_filename)

        if not os.path.exists(image_path):
            return jsonify({'message': 'No processed image found'}), 404

        return send_file(image_path, mimetype='image/png')

    except Exception as e:
        return jsonify({'message': 'Error fetching image', 'error': str(e)}), 500

from threading import Thread

def run_flask():
    app.run(debug=False, host='0.0.0.0', port=5001, use_reloader=False)

# Run Flask in a background thread
flask_thread = Thread(target=run_flask)
flask_thread.start()

import torch
import torch.nn as nn
from PIL import Image
import torchvision.transforms as transforms

def skip(num_input_channels=3, num_output_channels=3,
         num_channels_down=[128, 128, 128, 128, 128],
         num_channels_up=[128, 128, 128, 128, 128],
         num_channels_skip=[4, 4, 4, 4, 4],
         filter_size_down=3, filter_size_up=3, filter_skip_size=1,
         need_sigmoid=True, need_bias=True,
         pad='reflection', upsample_mode='nearest',
         downsample_mode='stride', act_fun='LeakyReLU',
         need1x1_up=True):

    assert len(num_channels_down) == len(num_channels_up) == len(num_channels_skip)
    n_scales = len(num_channels_down)

    def act(name='LeakyReLU'):
        if name == 'LeakyReLU':
            return nn.LeakyReLU(0.2, inplace=True)
        elif name == 'ReLU':
            return nn.ReLU(inplace=True)
        elif name == 'ELU':
            return nn.ELU(inplace=True)
        else:
            return nn.Identity()

    def bn(num_features):
        return nn.BatchNorm2d(num_features)

    def conv(in_f, out_f, kernel_size, stride=1, bias=True, pad='zero'):
        pad_val = (kernel_size - 1) // 2
        if pad == 'reflection':
            layers = [nn.ReflectionPad2d(pad_val)]
            pad_val = 0
        else:
            layers = []

        layers.append(nn.Conv2d(in_f, out_f, kernel_size, stride, padding=pad_val, bias=bias))
        return nn.Sequential(*layers)

    input_depth = num_input_channels
    model = nn.Sequential()
    model_tmp = model

    for i in range(n_scales):
        deeper = nn.Sequential()
        skip = nn.Sequential()
        model_tmp.add_module(f"skip_{i}", skip)
        model_tmp.add_module(f"deeper_{i}", deeper)

        if num_channels_skip[i] != 0:
            skip.add_module(f"conv_skip_{i}", conv(input_depth, num_channels_skip[i], filter_skip_size, bias=need_bias, pad=pad))
            skip.add_module(f"bn_skip_{i}", bn(num_channels_skip[i]))
            skip.add_module(f"act_skip_{i}", act(act_fun))

        deeper.add_module(f"conv_down_{i}_1", conv(input_depth, num_channels_down[i], filter_size_down, stride=2, bias=need_bias, pad=pad))
        deeper.add_module(f"bn_down_{i}_1", bn(num_channels_down[i]))
        deeper.add_module(f"act_down_{i}_1", act(act_fun))

        deeper.add_module(f"conv_down_{i}_2", conv(num_channels_down[i], num_channels_down[i], filter_size_down, bias=need_bias, pad=pad))
        deeper.add_module(f"bn_down_{i}_2", bn(num_channels_down[i]))
        deeper.add_module(f"act_down_{i}_2", act(act_fun))

        deeper_main = nn.Sequential()

        if i == n_scales - 1:
            k = num_channels_down[i]
        else:
            deeper.add_module(f"sub_deeper_{i}", deeper_main)
            k = num_channels_up[i + 1]

        deeper.add_module(f"upsample_{i}", nn.Upsample(scale_factor=2, mode=upsample_mode))

        model_tmp.add_module(f"conv_up_{i}_1", conv(num_channels_skip[i] + k, num_channels_up[i], filter_size_up, bias=need_bias, pad=pad))
        model_tmp.add_module(f"bn_up_{i}_1", bn(num_channels_up[i]))
        model_tmp.add_module(f"act_up_{i}_1", act(act_fun))

        if need1x1_up:
            model_tmp.add_module(f"conv_up_{i}_2", conv(num_channels_up[i], num_channels_up[i], 1, bias=need_bias, pad=pad))
            model_tmp.add_module(f"bn_up_{i}_2", bn(num_channels_up[i]))
            model_tmp.add_module(f"act_up_{i}_2", act(act_fun))

        input_depth = num_channels_down[i]
        model_tmp = deeper_main

    model.add_module("final_conv", conv(num_channels_up[0], num_output_channels, 1, bias=need_bias, pad=pad))
    if need_sigmoid:
        model.add_module("sigmoid", nn.Sigmoid())

    return model

def get_net(input_depth, NET_TYPE='skip', pad='reflection',
            skip_n33d=128, skip_n33u=128, skip_n11=4, num_scales=5,
            upsample_mode='bilinear', n_channels=3):

    if NET_TYPE == 'skip':
        net = skip(num_input_channels=input_depth, num_output_channels=n_channels,
                   num_channels_down=[skip_n33d] * num_scales,
                   num_channels_up=[skip_n33u] * num_scales,
                   num_channels_skip=[skip_n11] * num_scales,
                   filter_size_down=3, filter_size_up=3, filter_skip_size=1,
                   need_sigmoid=True, need_bias=True,
                   pad=pad, upsample_mode=upsample_mode,
                   downsample_mode='stride', act_fun='LeakyReLU',
                   need1x1_up=True)
        return net
    else:
        raise ValueError(f"Unknown NET_TYPE: {NET_TYPE}")


def load_dip_model(model_path="hist_dip_model.pth",
                   input_depth=32):
    """
    Loads the DIP model architecture and its saved weights.
    """
    # Instantiate the architecture
    net = get_net(
        input_depth=input_depth,
        NET_TYPE='skip',
        pad='reflection',
        skip_n33d=128,
        skip_n33u=128,
        skip_n11=4,
        num_scales=5,
        upsample_mode='bilinear'
    )

    # Load the weights
    net.load_state_dict(torch.load(model_path),strict=False)
    net.eval()  # Set to inference mode
    return net